server:
  host: 127.0.0.1
cloudSlicer:
  apiHost: http://api.proventoprint.com
folder:
  uploads: /sdcard/AstroBox/uploads
  timelapse: /sdcard/AstroBox/timelapse
  timelapse_tmp: /sdcard/AstroBox/timelapse/tmp
  logs: /var/log/astrobox
  watched: /sdcard/AstroBox/watched
system:
  actions:
  - action: shutdown
    command: shutdown -H now
